services:
  spring_app:
    image: your-dockerhub-username/movieapp:latest
    container_name: spring_app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ALLOWED_ORIGIN_FOR_SOCKETS: ${ALLOWED_ORIGIN_FOR_SOCKETS}
      JAVA_OPTS: ${JAVA_OPTS}
