version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: movieapp
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: spring_app
    restart: always
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/movieapp
      DB_USERNAME: appuser
      DB_PASSWORD: apppass
      ALLOWED_ORIGIN_FOR_SOCKETS: http://localhost:3000
    ports:
      - "8080:8080"
    command: ["java", "-jar", "app.jar"]

volumes:
  db_data:
